# Generated by Django 5.0.1 on 2024-01-18 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date_finish",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 18, 20, 31, 58, 293069, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
